name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: npm install --save-dev chromedriver

      - name: Start Xvfb
        run: Xvfb :99 -ac -screen 0 1280x1024x16 &

      - name: Set DISPLAY
        run: export DISPLAY=:99

      - name: Update Chrome Driver
        run: npx webdriver-manager update

      - name: Run WebdriverIO tests
        run: npx wdio run wdio.conf.ts
